### ISSUE TITLE
In nc task, what does the "cstr_nc" mean in preprocess.py?

### ISSUE THREAD

**Issue by qzzdd** [AutoML-4Paradigm/DiffMG#1]
I am wondering what does "cstr_nc" mean in preprocess.py? What does it have to do with the dataset?

**Comment by skeletondyh** [comment]
It means "constraint". Please refer to Section 4.1.2 in the paper. We constrain candidate edge types for some links in the search space.

**Comment by flipside17** [comment]
I am wondering what does arch.py mean in lp project?

**Comment by flipside17** [comment]
I am wodering How did you get arch.py in lp project?

**Comment by skeletondyh** [comment]
It's just a record of the selected architectures after the search. Please open a new issue for a separate question.

**Comment by flipside17** [comment]
dear author,I wondering why did you choose '1' and '4' ( "DBLP" : [1, 4]) in cstr_nc .What do '1' and '4'mean?

**Comment by skeletondyh** [comment]
"1" and "4" are indexes of edge types. "1" denotes edge type "Paper -> Author", and "4" denotes identity. The specific mapping depends on how you order edge types. Please refer to  Section 4.1.2 of the paper for why we have such constraints.

**Comment by flipside17** [comment]
I wodering how to get arch.py in lp project?I I choose the YELP dataset to run the train_search of lp project. After running 100 epochs,the Source arch is  ([[8, 8, 0, 0]], [[4, 7, 10, 10, 10, 10]]) and the Target arch is ([[1, 1, 9, 5]], [[5, 10, 8, 10, 10, 10]].This is inconsistent with the data in the arch.py for Yelp
"Yelp" : {
        "source" : ([[6, 5, 4, 3]], [[9, 4, 10, 10, 9, 9]]),
        "target" : ([[4, 5, 9, 2]], [[3, 2, 8, 10, 5, 10]])
    }

**Comment by skeletondyh** [comment]
You need to select the arch with the lowest validation error according to the search log

**Comment by flipside17** [comment]
excuse me,I found some minor issues that the arch.py documents the schema of the douban dataset：
"Douban_Movie" : {
        "source" : ([[5, 7, 0, 1]], [[6, 0, 3, 11, 12, 11]]),
        "target" : ([[10, 0, 9, 2]], [[7, 5, 6, 12, 11, 5]]) }
In figure 3(b) of the paper, the meta graph (above) has a link of(H(0)->H(2)) which is masked as I, but in "source" is masked as 6(the edge type is Aam). Also the meta graph (below) has a link of(H(1)->H(3)) which is masked as I, but in "target" is masked as 6

**Comment by skeletondyh** [comment]
These patterns are effectively equivalent.

For the link H(0)->H(2) in the meta graph above, propagation "movie->actor" would update representations of actors and leave others unchanged. However, the target node type is user (U). Actors don't contribute to subsequent computation of user representations, so whether H(0)->H(2) is Identity or "movie->actor" has the same effect on user representations

For the meta graph below, the case is similar.
